branch-defaults:
  master:
    environment: Sample-env
  test:
    environment: Sample-env
environment-defaults:
  Sample-env:
    branch: null
    repository: null
global:
  application_name: You Jump I Jump
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-west-2::platform/PHP 7.0 running on
    64bit Amazon Linux/2.4.0
  default_region: us-west-2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
